[package]
name = "linux_x86_64"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
posix_x86_64 = { path = "../../arch/posix_x86_64" }
kernel = { path = "../../kernel" }
