[package]
name = "posix_x86_64"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../../kernel" }
nix = "^0.18.0"
